# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: receipe-nutrition-finder-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: receipe-nutrition-finder
#   template:
#     metadata:
#       labels:
#         app: receipe-nutrition-finder
#     spec:
#       imagePullSecrets:
#         - name: nexus-creds
#       containers:
#         - name: receipe-nutrition-finder
#           # IMPORTANT: Replace this with the full URL to your image in the Nexus repository if it differs
#           image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/2401102/receipe-nutrition-finder:v1
#           ports:
#             # The port your application container is listening on. Adjust if your app uses a different port.
#             - containerPort: 80
apiVersion: v1
kind: Namespace
metadata:
  name: "2401102"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: receipe-nutrition-finder-deployment
  namespace: "2401102"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receipe-nutrition-finder
  template:
    metadata:
      labels:
        app: receipe-nutrition-finder
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
        - name: receipe-nutrition-finder
          image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/2401102/receipe-nutrition-finder:v1
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: receipe-nutrition-finder-service
  namespace: "2401102"
spec:
  selector:
    app: receipe-nutrition-finder
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: ClusterIP
