apiVersion: v1
kind: Service
metadata:
  name: recipe-finder-service
spec:
  selector:
    app: recipe-finder
  ports:
    - protocol: TCP
      # The port the service will be available on within the cluster.
      port: 80
      # The port on the pod that the service will forward traffic to. Match this with your containerPort in the deployment.
      targetPort: 80
  # Type of service. Use NodePort or LoadBalancer if you need external access to your application.
  type: ClusterIP
